import { TEXTES } from './textes'

const FR = {
  title: 'Audit de design system',
  role: 'Outil — colle ou dépose tes tokens, obtiens un rapport chiffré',
  mastheadCenter: 'ARCHIVE DU LAB //// DOSSIER PROJET',
  mastheadRight: 'MISRAN LABS',
  mastheadRightSub: 'ARCHIVE VISUEL',
  stampLabel: 'MISRAN · LABS · ARCHIVE ·',
  clearance: 'NIVEAU DE LECTURE — PUBLIC',
  tagline: 'LE DESIGN EST UNE INTENTION. LES DÉTAILS SONT TOUT.',
  intro:
    "Cet outil lit les fichiers de tokens d'un design system et signale ce qui ne tient pas : références cassées ou circulaires, valeurs codées en dur, doublons, couleurs quasi identiques, tokens inutilisés. L'analyse suit des règles fixes, sans IA : deux passages sur le même fichier donnent le même rapport.",
  formats: 'Formats acceptés : CSS (propriétés personnalisées --nom), JSON W3C DTCG, JSON Tokens Studio. Le format est détecté automatiquement.',
  inputTitle: 'ENTRÉE',
  pasteLabel: 'COLLER UN FICHIER',
  pastePlaceholder: ':root {\n  --couleur-marque: #e26a50;\n  --bouton-fond: var(--couleur-marque);\n}',
  pickLabel: 'OU CHARGER DES FICHIERS (.css, .scss, .json)',
  pickButton: 'Choisir des fichiers',
  dropHint: 'Tu peux aussi déposer des fichiers ici.',
  filesTitle: 'FICHIERS CHARGÉS',
  remove: 'Retirer',
  unknownFormat: 'format non reconnu',
  formatNames: { css: 'CSS', dtcg: 'JSON DTCG', 'tokens-studio': 'JSON Tokens Studio' },
  tokensCount: (n) => `${n} token${n > 1 ? 's' : ''}`,
  analyze: 'Analyser',
  examplesLabel: 'EXEMPLES',
  examples: { css: 'CSS', dtcg: 'DTCG', 'tokens-studio': 'Tokens Studio' },
  auditSite: 'Auditer les tokens de ce site',
  pastedName: 'texte-colle.txt',
  resultsTitle: 'RÉSULTAT',
  warningsTitle: 'MESSAGES DE LECTURE',
  noTokens: "Aucun token trouvé : il n'y a rien à auditer. Vérifie le format du fichier.",
  allClear: 'Aucun constat : ces tokens sont cohérents selon les huit règles de l’outil.',
  summary: {
    files: 'FICHIERS',
    tokens: 'TOKENS',
    healthy: 'TOKENS SAINS',
    healthyNote: 'sans erreur ni avertissement',
    byType: 'PAR TYPE',
    byFormat: 'PAR FORMAT',
    unknownType: 'sans type',
  },
  filterLabel: 'FILTRER PAR GRAVITÉ',
  severities: { erreur: 'Erreur', avertissement: 'Avertissement', info: 'Info' },
  severityCount: (n) => `${n}`,
  ruleWord: 'Règle',
  findingsCount: (n) => `${n} constat${n > 1 ? 's' : ''}`,
  showMore: (n) => `Afficher les ${n} autres`,
  moreTokens: (n) => `+${n}`,
  line: 'ligne',
  noMatch: 'Aucun constat pour ce filtre.',
  copyReport: 'Copier le rapport',
  copied: 'Rapport copié',
  reportTitle: "Rapport d'audit des tokens",
  reportSummary: 'Résumé',
  reportWarnings: 'Messages de lecture',
  rules: {
    R1: { titre: 'Référence cassée', explication: "Un token en référence un autre qui n'est défini nulle part : sa valeur ne peut pas être résolue. En CSS, une valeur de secours ramène la gravité à un avertissement." },
    R2: { titre: 'Référence circulaire', explication: 'Des tokens se réfèrent les uns aux autres en boucle : aucun ne peut recevoir de valeur finale.' },
    R3: { titre: 'Valeur codée en dur', explication: "Une déclaration CSS porte une couleur ou une longueur en px littérale au lieu de passer par un token. Le style échappe au design system." },
    R4: { titre: 'Doublon de valeur', explication: 'Plusieurs tokens de même contexte portent exactement la même valeur brute. Souvent, l’un devrait être l’alias de l’autre.' },
    R5: { titre: 'Couleurs quasi identiques', explication: 'Deux couleurs opaques diffèrent de trois niveaux ou moins par composante : une différence invisible, souvent un oubli d’harmonisation.' },
    R6: { titre: 'Token inutilisé', explication: "Un token n'est référencé nulle part dans les fichiers fournis. Il peut être utilisé ailleurs (code, autres fichiers) : à vérifier avant de le supprimer." },
    R7: { titre: "Chaîne d'alias trop longue", explication: 'Plus de trois références successives avant la valeur finale : retrouver la valeur réelle devient pénible.' },
    R8: { titre: 'Type manquant', explication: "Un token JSON n'a pas de type, ni propre ni hérité de son groupe : les outils ne savent pas ce qu'il représente." },
  },
  ctaTitle: 'Besoin d’un audit complet de votre design system ?',
  ctaText: "Cet outil fait le relevé, la note sur 7 axes et la matrice des priorités, à partir des fichiers. Un audit complet y ajoute ce qu’aucun fichier ne montre : l’entretien avec l’équipe, la parité Figma ↔ code, l’usage réel du produit, puis l’accompagnement pendant les corrections.",
  ctaLink: 'Me contacter sur LinkedIn',
}

const EN = {
  title: 'Design system audit',
  role: 'Tool — paste or drop your tokens, get a detailed report',
  mastheadCenter: 'LAB ARCHIVE //// PROJECT FILE',
  mastheadRight: 'MISRAN LABS',
  mastheadRightSub: 'VISUAL ARCHIVE',
  stampLabel: 'MISRAN · LABS · ARCHIVE ·',
  clearance: 'CLEARANCE LEVEL — PUBLIC',
  tagline: 'DESIGN IS INTENT. DETAILS ARE EVERYTHING.',
  intro:
    'This tool reads a design system token file and reports what does not work: broken or circular references, hard-coded values, duplicates, near-identical colors, unused tokens. Analysis follows fixed rules, no AI: two passes on the same file yield the same report.',
  formats: 'Accepted formats: CSS (custom properties --name), W3C JSON DTCG, JSON Tokens Studio. Format is auto-detected.',
  inputTitle: 'INPUT',
  pasteLabel: 'PASTE A FILE',
  pastePlaceholder: ':root {\n  --brand-color: #e26a50;\n  --button-background: var(--brand-color);\n}',
  pickLabel: 'OR LOAD FILES (.css, .scss, .json)',
  pickButton: 'Choose files',
  dropHint: 'You can also drop files here.',
  filesTitle: 'LOADED FILES',
  remove: 'Remove',
  unknownFormat: 'unrecognized format',
  formatNames: { css: 'CSS', dtcg: 'JSON DTCG', 'tokens-studio': 'JSON Tokens Studio' },
  tokensCount: (n) => `${n} token${n > 1 ? 's' : ''}`,
  analyze: 'Analyze',
  examplesLabel: 'EXAMPLES',
  examples: { css: 'CSS', dtcg: 'DTCG', 'tokens-studio': 'Tokens Studio' },
  auditSite: "Audit this site's tokens",
  pastedName: 'pasted-text.txt',
  resultsTitle: 'RESULT',
  warningsTitle: 'READING MESSAGES',
  noTokens: 'No tokens found: there is nothing to audit. Check your file format.',
  allClear: 'All clear: these tokens are consistent across the eight rules.',
  summary: {
    files: 'FILES',
    tokens: 'TOKENS',
    healthy: 'HEALTHY TOKENS',
    healthyNote: 'no errors or warnings',
    byType: 'BY TYPE',
    byFormat: 'BY FORMAT',
    unknownType: 'no type',
  },
  filterLabel: 'FILTER BY SEVERITY',
  severities: { erreur: 'Error', avertissement: 'Warning', info: 'Info' },
  severityCount: (n) => `${n}`,
  ruleWord: 'Rule',
  findingsCount: (n) => `${n} finding${n > 1 ? 's' : ''}`,
  showMore: (n) => `Show ${n} more`,
  moreTokens: (n) => `+${n}`,
  line: 'line',
  noMatch: 'No findings for this filter.',
  copyReport: 'Copy report',
  copied: 'Report copied',
  reportTitle: 'Token audit report',
  reportSummary: 'Summary',
  reportWarnings: 'Reading messages',
  rules: {
    R1: { titre: 'Broken reference', explication: 'A token references another token that is not defined anywhere: its value cannot be resolved. In CSS, a fallback value drops the severity to a warning.' },
    R2: { titre: 'Circular reference', explication: 'Tokens reference each other in a loop: none can receive a final value.' },
    R3: { titre: 'Hard-coded value', explication: 'A CSS declaration uses a literal color or px length instead of a token. The style escapes the design system.' },
    R4: { titre: 'Duplicate value', explication: 'Multiple tokens in the same context have exactly the same raw value. Often, one should be an alias of the other.' },
    R5: { titre: 'Near-identical colors', explication: 'Two opaque colors differ by three levels or less per component: a difference invisible to the eye, often a missed harmonization.' },
    R6: { titre: 'Unused token', explication: 'A token is not referenced anywhere in the supplied files. It may be used elsewhere (code, other files): verify before deleting.' },
    R7: { titre: 'Alias chain too long', explication: 'More than three successive references before the final value: finding the real value becomes tedious.' },
    R8: { titre: 'Missing type', explication: 'A JSON token lacks a type, neither its own nor inherited from its group: tools cannot tell what it represents.' },
  },
  ctaTitle: 'Need a full audit of your design system?',
  ctaText: "This tool does the survey, the 7-axis score and the priority matrix, from the files. A full audit adds what no file shows: the interview with the team, Figma ↔ code parity, how the product is really used, then support while the fixes are made.",
  ctaLink: 'Contact me on LinkedIn',
}

// Textes de la page + textes ajoutés par le mode GitHub (src/lab/projects/audit/textes.js).
export const CONTENT = { fr: { ...FR, ...TEXTES.fr }, en: { ...EN, ...TEXTES.en } }
